name: microscopy-data 
channels:
- conda-forge
dependencies:
- conda-forge::python>=3.10.6
- conda-forge::jupyterlab
- conda-forge::pandas=>1.2
- conda-forge::plotnine=>0.9.0
- conda-forge::pyarrow=>6.0.1
- conda-forge::black
