name: microscopy-data
channels:
- conda-forge
dependencies:
- conda-forge::python>=3.8
- conda-forge::jupyterlab
- conda-forge::pandas
- conda-forge::plotnine
- conda-forge::pyarrow
- conda-forge::black
- conda-forge::scipy
- conda-forge::tqdm
- conda-forge::matplotlib==3.5.3
